//
// Created by user on 08.11.2021.
//

#ifndef BSI_RELIABILITY_CALCULATOR_FINDING_RELIABILITY_OF_EACH_ELEMENT_CONNECTED_IN_PARALLEL_H
#define BSI_RELIABILITY_CALCULATOR_FINDING_RELIABILITY_OF_EACH_ELEMENT_CONNECTED_IN_PARALLEL_H
double finding_reliability(int num_of_components, double sys_reliability);
#endif //BSI_RELIABILITY_CALCULATOR_FINDING_RELIABILITY_OF_EACH_ELEMENT_CONNECTED_IN_PARALLEL_H
