#ifndef BSI_RELIABILITY_CALCULATOR_COMPARING_PROBABILITY_OF_SUCCESS_OF_EVENTS_H
#define BSI_RELIABILITY_CALCULATOR_COMPARING_PROBABILITY_OF_SUCCESS_OF_EVENTS_H
void probability_of_success(int n, int k, int n1, int k1);
#endif
