#ifndef BSI_RELIABILITY_CALCULATOR_PROBABILITY_OF_PASSING_INTERVIEW_H
#define BSI_RELIABILITY_CALCULATOR_PROBABILITY_OF_PASSING_INTERVIEW_H
void probability_of_passing(int num, int den, int num1, int den1);
#endif
