#ifndef BSI_RELIABILITY_CALCULATOR_PROBABILITY_OF_ELECTRICITY_ON_ANY_DAY_H
#define BSI_RELIABILITY_CALCULATOR_PROBABILITY_OF_ELECTRICITY_ON_ANY_DAY_H
void probability_of_availability_of_electricity(double event_A, double event_B);
#endif
